version: 2
project_name: gatecrash

before:
  hooks:
    - sh -c "mkdir -p web/static/js web/static/css web/static/fonts/roboto"
    - sh -c "test -f web/static/css/bulma.min.css || curl -sL https://cdn.jsdelivr.net/npm/bulma/css/bulma.min.css -o web/static/css/bulma.min.css"
    - sh -c "test -f web/static/js/htmx.min.js || curl -sL https://unpkg.com/htmx.org/dist/htmx.min.js -o web/static/js/htmx.min.js"
    - sh -c "test -f web/static/js/htmx-sse.js || curl -sL https://unpkg.com/htmx-ext-sse/sse.js -o web/static/js/htmx-sse.js"
    - sh -c "test -f web/static/fonts/roboto/roboto-regular.woff2 || curl -sL 'https://fonts.gstatic.com/s/roboto/v47/KFOMCnqEu92Fr1ME7kSn66aGLdTylUAMQXC89YmC2DPNWubEbGmT.woff2' -o web/static/fonts/roboto/roboto-regular.woff2"
    - sh -c "test -f web/static/fonts/roboto/roboto-bold.woff2 || curl -sL 'https://fonts.gstatic.com/s/roboto/v47/KFOMCnqEu92Fr1ME7kSn66aGLdTylUAMQXC89YmC2DPNWuaabWmT.woff2' -o web/static/fonts/roboto/roboto-bold.woff2"
    - go mod tidy

builds:
  - id: gatecrash
    main: ./cmd/gatecrash
    binary: gatecrash
    env: [CGO_ENABLED=0]
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w -X main.Version={{.Version}}

archives:
  - id: gatecrash
    builds: [gatecrash]
    name_template: "gatecrash_{{ .Os }}_{{ .Arch }}"
    format: binary

dockers:
  - ids: [gatecrash]
    goos: linux
    goarch: amd64
    dockerfile: Dockerfile.goreleaser
    use: buildx
    build_flag_templates: ["--platform=linux/amd64"]
    image_templates:
      - "ghcr.io/jclement/gatecrash:{{ .Version }}-amd64"
      - "ghcr.io/jclement/gatecrash:latest-amd64"

  - ids: [gatecrash]
    goos: linux
    goarch: arm64
    dockerfile: Dockerfile.goreleaser
    use: buildx
    build_flag_templates: ["--platform=linux/arm64"]
    image_templates:
      - "ghcr.io/jclement/gatecrash:{{ .Version }}-arm64"
      - "ghcr.io/jclement/gatecrash:latest-arm64"

docker_manifests:
  - name_template: "ghcr.io/jclement/gatecrash:{{ .Version }}"
    image_templates:
      - "ghcr.io/jclement/gatecrash:{{ .Version }}-amd64"
      - "ghcr.io/jclement/gatecrash:{{ .Version }}-arm64"
  - name_template: "ghcr.io/jclement/gatecrash:latest"
    image_templates:
      - "ghcr.io/jclement/gatecrash:latest-amd64"
      - "ghcr.io/jclement/gatecrash:latest-arm64"

changelog:
  sort: asc
  filters:
    exclude: ["^docs:", "^test:", "^ci:", "^chore:"]

release:
  prerelease: auto
  footer: |
    ## Docker

    ```bash
    docker pull ghcr.io/jclement/gatecrash:{{ .Version }}
    ```

    ## Quick Install (Linux)
    ```bash
    curl -fsSL https://raw.githubusercontent.com/jclement/gatecrash/main/deploy/install.sh | sh
    ```
