FROM alpine:3.23
RUN apk add --no-cache ca-certificates tzdata && \
    adduser -D -u 1000 gatecrash && \
    mkdir -p /etc/gatecrash/certs && \
    chown -R gatecrash:gatecrash /etc/gatecrash
WORKDIR /app
COPY gatecrash .
EXPOSE 443 80
VOLUME ["/etc/gatecrash"]
USER gatecrash
CMD ["./gatecrash", "server", "--config", "/etc/gatecrash/gatecrash.toml"]
